# Generated by Django 5.1.1 on 2025-06-24 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_banner_options_remove_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='type_tk',
        ),
    ]
