# Generated by Django 5.1.1 on 2025-06-24 14:55

import apps.utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_type_remove_product_type_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=apps.utils.fields.CompressedImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
